version: "3.9"
name: "flame"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flame
    ports:
      - "5445:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
volumes:
  pgdata: