version: "3.9"
name: "flame"
services:
  pg-account:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: account
    ports:
      - "5445:5432"
    networks:
      - backend
    volumes:
      - ./data/account:/var/lib/postgresql/data
  pg-swipe:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: swipe
    ports:
      - "5444:5432"
    networks:
      - backend
    volumes:
      - ./data/swipe:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge
volumes:
  pgdata: