services:
  api:
    address: "localhost:7300"
  account:
    address: "localhost:7301"
database:
  dsn: "port=5445 host=localhost user=user dbname=test password=123456 sslmode=disable"
auth:
  jwt: "token*jwt-!gh"
public:
  host : "localhost"
  port :  7300
s3:
  bucket: "flame-dev"
  endpoint: "https://hb.ru-msk.vkcloud-storage.ru"