// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.3
// source: matching.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Age           *int32                 `protobuf:"varint,3,opt,name=Age,json=age,proto3,oneof" json:"Age,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=City,json=city,proto3,oneof" json:"City,omitempty"`
	Gender        *string                `protobuf:"bytes,5,opt,name=Gender,json=gender,proto3,oneof" json:"Gender,omitempty"`
	Photo         *UserPhoto             `protobuf:"bytes,6,opt,name=Photo,json=photo,proto3" json:"Photo,omitempty"`
	Distance      int32                  `protobuf:"varint,7,opt,name=Distance,json=distance,proto3" json:"Distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMatch) Reset() {
	*x = UserMatch{}
	mi := &file_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMatch) ProtoMessage() {}

func (x *UserMatch) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMatch.ProtoReflect.Descriptor instead.
func (*UserMatch) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{0}
}

func (x *UserMatch) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMatch) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UserMatch) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UserMatch) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UserMatch) GetPhoto() *UserPhoto {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *UserMatch) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type GetMatchingUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingUsersReq) Reset() {
	*x = GetMatchingUsersReq{}
	mi := &file_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingUsersReq) ProtoMessage() {}

func (x *GetMatchingUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingUsersReq.ProtoReflect.Descriptor instead.
func (*GetMatchingUsersReq) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{1}
}

func (x *GetMatchingUsersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMatchingUsersReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetMatchingUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserMatch           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingUsersRes) Reset() {
	*x = GetMatchingUsersRes{}
	mi := &file_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingUsersRes) ProtoMessage() {}

func (x *GetMatchingUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingUsersRes.ProtoReflect.Descriptor instead.
func (*GetMatchingUsersRes) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchingUsersRes) GetUsers() []*UserMatch {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_matching_proto protoreflect.FileDescriptor

var file_matching_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd6, 0x01, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x15, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x88, 0x01,
	0x01, 0x12, 0x1b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x02, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x20,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x41, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x43, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x32, 0x4a, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x42, 0x0e, 0x5a, 0x0c, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_matching_proto_rawDescOnce sync.Once
	file_matching_proto_rawDescData []byte
)

func file_matching_proto_rawDescGZIP() []byte {
	file_matching_proto_rawDescOnce.Do(func() {
		file_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)))
	})
	return file_matching_proto_rawDescData
}

var file_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_matching_proto_goTypes = []any{
	(*UserMatch)(nil),           // 0: UserMatch
	(*GetMatchingUsersReq)(nil), // 1: GetMatchingUsersReq
	(*GetMatchingUsersRes)(nil), // 2: GetMatchingUsersRes
	(*UserPhoto)(nil),           // 3: UserPhoto
}
var file_matching_proto_depIdxs = []int32{
	3, // 0: UserMatch.Photo:type_name -> UserPhoto
	0, // 1: GetMatchingUsersRes.users:type_name -> UserMatch
	1, // 2: Matching.GetMatchingUsers:input_type -> GetMatchingUsersReq
	2, // 3: Matching.GetMatchingUsers:output_type -> GetMatchingUsersRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matching_proto_init() }
func file_matching_proto_init() {
	if File_matching_proto != nil {
		return
	}
	file_account_proto_init()
	file_matching_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_proto_goTypes,
		DependencyIndexes: file_matching_proto_depIdxs,
		MessageInfos:      file_matching_proto_msgTypes,
	}.Build()
	File_matching_proto = out.File
	file_matching_proto_goTypes = nil
	file_matching_proto_depIdxs = nil
}
