// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: matching.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Matching_GetMatchingUsers_FullMethodName = "/Matching/GetMatchingUsers"
)

// MatchingClient is the client API for Matching service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingClient interface {
	GetMatchingUsers(ctx context.Context, in *GetMatchingUsersReq, opts ...grpc.CallOption) (*GetMatchingUsersRes, error)
}

type matchingClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingClient(cc grpc.ClientConnInterface) MatchingClient {
	return &matchingClient{cc}
}

func (c *matchingClient) GetMatchingUsers(ctx context.Context, in *GetMatchingUsersReq, opts ...grpc.CallOption) (*GetMatchingUsersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchingUsersRes)
	err := c.cc.Invoke(ctx, Matching_GetMatchingUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServer is the server API for Matching service.
// All implementations must embed UnimplementedMatchingServer
// for forward compatibility.
type MatchingServer interface {
	GetMatchingUsers(context.Context, *GetMatchingUsersReq) (*GetMatchingUsersRes, error)
	mustEmbedUnimplementedMatchingServer()
}

// UnimplementedMatchingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServer struct{}

func (UnimplementedMatchingServer) GetMatchingUsers(context.Context, *GetMatchingUsersReq) (*GetMatchingUsersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchingUsers not implemented")
}
func (UnimplementedMatchingServer) mustEmbedUnimplementedMatchingServer() {}
func (UnimplementedMatchingServer) testEmbeddedByValue()                  {}

// UnsafeMatchingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServer will
// result in compilation errors.
type UnsafeMatchingServer interface {
	mustEmbedUnimplementedMatchingServer()
}

func RegisterMatchingServer(s grpc.ServiceRegistrar, srv MatchingServer) {
	// If the following call pancis, it indicates UnimplementedMatchingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Matching_ServiceDesc, srv)
}

func _Matching_GetMatchingUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchingUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServer).GetMatchingUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matching_GetMatchingUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServer).GetMatchingUsers(ctx, req.(*GetMatchingUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Matching_ServiceDesc is the grpc.ServiceDesc for Matching service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matching_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Matching",
	HandlerType: (*MatchingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatchingUsers",
			Handler:    _Matching_GetMatchingUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching.proto",
}
