// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.3
// source: swipes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrUpdateSwipeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       int64                  `protobuf:"varint,1,opt,name=UserId1,proto3" json:"UserId1,omitempty"`
	UserId2       int64                  `protobuf:"varint,2,opt,name=UserId2,proto3" json:"UserId2,omitempty"`
	IsLike        bool                   `protobuf:"varint,3,opt,name=IsLike,proto3" json:"IsLike,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateSwipeReq) Reset() {
	*x = CreateOrUpdateSwipeReq{}
	mi := &file_swipes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateSwipeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateSwipeReq) ProtoMessage() {}

func (x *CreateOrUpdateSwipeReq) ProtoReflect() protoreflect.Message {
	mi := &file_swipes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateSwipeReq.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateSwipeReq) Descriptor() ([]byte, []int) {
	return file_swipes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrUpdateSwipeReq) GetUserId1() int64 {
	if x != nil {
		return x.UserId1
	}
	return 0
}

func (x *CreateOrUpdateSwipeReq) GetUserId2() int64 {
	if x != nil {
		return x.UserId2
	}
	return 0
}

func (x *CreateOrUpdateSwipeReq) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

type CreateOrUpdateSwipeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateSwipeRes) Reset() {
	*x = CreateOrUpdateSwipeRes{}
	mi := &file_swipes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateSwipeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateSwipeRes) ProtoMessage() {}

func (x *CreateOrUpdateSwipeRes) ProtoReflect() protoreflect.Message {
	mi := &file_swipes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateSwipeRes.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateSwipeRes) Descriptor() ([]byte, []int) {
	return file_swipes_proto_rawDescGZIP(), []int{1}
}

type GetUnreadSwipesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadSwipesReq) Reset() {
	*x = GetUnreadSwipesReq{}
	mi := &file_swipes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadSwipesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadSwipesReq) ProtoMessage() {}

func (x *GetUnreadSwipesReq) ProtoReflect() protoreflect.Message {
	mi := &file_swipes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadSwipesReq.ProtoReflect.Descriptor instead.
func (*GetUnreadSwipesReq) Descriptor() ([]byte, []int) {
	return file_swipes_proto_rawDescGZIP(), []int{2}
}

func (x *GetUnreadSwipesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUnreadSwipesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=UserIds,proto3" json:"UserIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadSwipesRes) Reset() {
	*x = GetUnreadSwipesRes{}
	mi := &file_swipes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadSwipesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadSwipesRes) ProtoMessage() {}

func (x *GetUnreadSwipesRes) ProtoReflect() protoreflect.Message {
	mi := &file_swipes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadSwipesRes.ProtoReflect.Descriptor instead.
func (*GetUnreadSwipesRes) Descriptor() ([]byte, []int) {
	return file_swipes_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadSwipesRes) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_swipes_proto protoreflect.FileDescriptor

var file_swipes_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x73, 0x77, 0x69, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x12, 0x16, 0x0a, 0x06,
	0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73,
	0x4c, 0x69, 0x6b, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x22, 0x2c,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x53, 0x77, 0x69, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x53, 0x77, 0x69, 0x70, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x32, 0x8e, 0x01, 0x0a,
	0x06, 0x53, 0x77, 0x69, 0x70, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x77, 0x69, 0x70, 0x65, 0x12, 0x17,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x53, 0x77, 0x69,
	0x70, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x53,
	0x77, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x53, 0x77, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_swipes_proto_rawDescOnce sync.Once
	file_swipes_proto_rawDescData []byte
)

func file_swipes_proto_rawDescGZIP() []byte {
	file_swipes_proto_rawDescOnce.Do(func() {
		file_swipes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swipes_proto_rawDesc), len(file_swipes_proto_rawDesc)))
	})
	return file_swipes_proto_rawDescData
}

var file_swipes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_swipes_proto_goTypes = []any{
	(*CreateOrUpdateSwipeReq)(nil), // 0: CreateOrUpdateSwipeReq
	(*CreateOrUpdateSwipeRes)(nil), // 1: CreateOrUpdateSwipeRes
	(*GetUnreadSwipesReq)(nil),     // 2: GetUnreadSwipesReq
	(*GetUnreadSwipesRes)(nil),     // 3: GetUnreadSwipesRes
}
var file_swipes_proto_depIdxs = []int32{
	0, // 0: Swipes.CreateOrUpdateSwipe:input_type -> CreateOrUpdateSwipeReq
	2, // 1: Swipes.GetUnreadSwipes:input_type -> GetUnreadSwipesReq
	1, // 2: Swipes.CreateOrUpdateSwipe:output_type -> CreateOrUpdateSwipeRes
	3, // 3: Swipes.GetUnreadSwipes:output_type -> GetUnreadSwipesRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swipes_proto_init() }
func file_swipes_proto_init() {
	if File_swipes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swipes_proto_rawDesc), len(file_swipes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swipes_proto_goTypes,
		DependencyIndexes: file_swipes_proto_depIdxs,
		MessageInfos:      file_swipes_proto_msgTypes,
	}.Build()
	File_swipes_proto = out.File
	file_swipes_proto_goTypes = nil
	file_swipes_proto_depIdxs = nil
}
